name: zerox-test

on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends pesign sbsigntool qemu-system-x86 mtools dosfstools libelf-dev
      - name: Update submodules
        id: update-submodules
        run: |
          make update
      - name: Do the build
        id: build
        run: |
          pwd
          ZERON_DIR=$PWD/zeron
          BUILD_DIR=$PWD/build-x86_64
          OUTPUT_DIR=$PWD/output-x86_64
          echo "BUILD_DIR=${BUILD_DIR}" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=${OUTPUT_DIR}" >> "$GITHUB_ENV"
          mkdir -p ${BUILD_DIR} ${OUTPUT_DIR}
          cd ${BUILD_DIR}
          make TOPDIR=.. -f ../Makefile VENDOR_CERT_FILE=${ZERON_DIR}/vendor_cert.der ARCH=x86_64 DESTDIR=${OUTPUT_DIR} EFIDIR=ZeronsoftN ENABLE_SHIM_HASH=true all install
      - name: zerox-boot onetime test
        run: |
          ls -al ${OUTPUT_DIR}/boot/efi/EFI/ZeronsoftN/shimx64.efi
          /bin/bash ./zeron/test-onetime/do-test-case01.sh ${OUTPUT_DIR}/boot/efi/EFI/ZeronsoftN/shimx64.efi
          /bin/bash ./zeron/test-onetime/do-test-case02.sh ${OUTPUT_DIR}/boot/efi/EFI/ZeronsoftN/shimx64.efi
